// AUTO-GENERATED by scripts/generate-countries.ts — do not edit.
export interface CountryInfo {
  code: string;
  name: string;
  flag: string;
}

export const COUNTRIES: Record<string, CountryInfo> = {
  "AF": { code: "AF", name: "Afghanistan", flag: "🇦🇫" },
  "AX": { code: "AX", name: "Åland Islands", flag: "🇦🇽" },
  "AL": { code: "AL", name: "Albania", flag: "🇦🇱" },
  "DZ": { code: "DZ", name: "Algeria", flag: "🇩🇿" },
  "AS": { code: "AS", name: "American Samoa", flag: "🇦🇸" },
  "AD": { code: "AD", name: "Andorra", flag: "🇦🇩" },
  "AO": { code: "AO", name: "Angola", flag: "🇦🇴" },
  "AI": { code: "AI", name: "Anguilla", flag: "🇦🇮" },
  "AG": { code: "AG", name: "Antigua & Barbuda", flag: "🇦🇬" },
  "AR": { code: "AR", name: "Argentina", flag: "🇦🇷" },
  "AM": { code: "AM", name: "Armenia", flag: "🇦🇲" },
  "AW": { code: "AW", name: "Aruba", flag: "🇦🇼" },
  "AU": { code: "AU", name: "Australia", flag: "🇦🇺" },
  "AT": { code: "AT", name: "Austria", flag: "🇦🇹" },
  "AZ": { code: "AZ", name: "Azerbaijan", flag: "🇦🇿" },
  "BS": { code: "BS", name: "Bahamas", flag: "🇧🇸" },
  "BH": { code: "BH", name: "Bahrain", flag: "🇧🇭" },
  "BD": { code: "BD", name: "Bangladesh", flag: "🇧🇩" },
  "BB": { code: "BB", name: "Barbados", flag: "🇧🇧" },
  "BY": { code: "BY", name: "Belarus", flag: "🇧🇾" },
  "BE": { code: "BE", name: "Belgium", flag: "🇧🇪" },
  "BZ": { code: "BZ", name: "Belize", flag: "🇧🇿" },
  "BJ": { code: "BJ", name: "Benin", flag: "🇧🇯" },
  "BM": { code: "BM", name: "Bermuda", flag: "🇧🇲" },
  "BT": { code: "BT", name: "Bhutan", flag: "🇧🇹" },
  "BO": { code: "BO", name: "Bolivia", flag: "🇧🇴" },
  "BA": { code: "BA", name: "Bosnia & Herzegovina", flag: "🇧🇦" },
  "BW": { code: "BW", name: "Botswana", flag: "🇧🇼" },
  "BR": { code: "BR", name: "Brazil", flag: "🇧🇷" },
  "VG": { code: "VG", name: "British Virgin Islands", flag: "🇻🇬" },
  "BN": { code: "BN", name: "Brunei", flag: "🇧🇳" },
  "BG": { code: "BG", name: "Bulgaria", flag: "🇧🇬" },
  "BF": { code: "BF", name: "Burkina Faso", flag: "🇧🇫" },
  "BI": { code: "BI", name: "Burundi", flag: "🇧🇮" },
  "KH": { code: "KH", name: "Cambodia", flag: "🇰🇭" },
  "CM": { code: "CM", name: "Cameroon", flag: "🇨🇲" },
  "CA": { code: "CA", name: "Canada", flag: "🇨🇦" },
  "CV": { code: "CV", name: "Cape Verde", flag: "🇨🇻" },
  "BQ": { code: "BQ", name: "Caribbean Netherlands", flag: "🇧🇶" },
  "KY": { code: "KY", name: "Cayman Islands", flag: "🇰🇾" },
  "CF": { code: "CF", name: "Central African Republic", flag: "🇨🇫" },
  "TD": { code: "TD", name: "Chad", flag: "🇹🇩" },
  "CL": { code: "CL", name: "Chile", flag: "🇨🇱" },
  "CN": { code: "CN", name: "China", flag: "🇨🇳" },
  "CX": { code: "CX", name: "Christmas Island", flag: "🇨🇽" },
  "CC": { code: "CC", name: "Cocos (Keeling) Islands", flag: "🇨🇨" },
  "CO": { code: "CO", name: "Colombia", flag: "🇨🇴" },
  "KM": { code: "KM", name: "Comoros", flag: "🇰🇲" },
  "CG": { code: "CG", name: "Congo - Brazzaville", flag: "🇨🇬" },
  "CD": { code: "CD", name: "Congo - Kinshasa", flag: "🇨🇩" },
  "CK": { code: "CK", name: "Cook Islands", flag: "🇨🇰" },
  "CR": { code: "CR", name: "Costa Rica", flag: "🇨🇷" },
  "CI": { code: "CI", name: "Côte d’Ivoire", flag: "🇨🇮" },
  "HR": { code: "HR", name: "Croatia", flag: "🇭🇷" },
  "CU": { code: "CU", name: "Cuba", flag: "🇨🇺" },
  "CW": { code: "CW", name: "Curaçao", flag: "🇨🇼" },
  "CY": { code: "CY", name: "Cyprus", flag: "🇨🇾" },
  "CZ": { code: "CZ", name: "Czechia", flag: "🇨🇿" },
  "DK": { code: "DK", name: "Denmark", flag: "🇩🇰" },
  "DJ": { code: "DJ", name: "Djibouti", flag: "🇩🇯" },
  "DM": { code: "DM", name: "Dominica", flag: "🇩🇲" },
  "DO": { code: "DO", name: "Dominican Republic", flag: "🇩🇴" },
  "EC": { code: "EC", name: "Ecuador", flag: "🇪🇨" },
  "EG": { code: "EG", name: "Egypt", flag: "🇪🇬" },
  "SV": { code: "SV", name: "El Salvador", flag: "🇸🇻" },
  "GQ": { code: "GQ", name: "Equatorial Guinea", flag: "🇬🇶" },
  "ER": { code: "ER", name: "Eritrea", flag: "🇪🇷" },
  "EE": { code: "EE", name: "Estonia", flag: "🇪🇪" },
  "SZ": { code: "SZ", name: "Eswatini", flag: "🇸🇿" },
  "ET": { code: "ET", name: "Ethiopia", flag: "🇪🇹" },
  "FK": { code: "FK", name: "Falkland Islands", flag: "🇫🇰" },
  "FO": { code: "FO", name: "Faroe Islands", flag: "🇫🇴" },
  "FJ": { code: "FJ", name: "Fiji", flag: "🇫🇯" },
  "FI": { code: "FI", name: "Finland", flag: "🇫🇮" },
  "FR": { code: "FR", name: "France", flag: "🇫🇷" },
  "GF": { code: "GF", name: "French Guiana", flag: "🇬🇫" },
  "PF": { code: "PF", name: "French Polynesia", flag: "🇵🇫" },
  "TF": { code: "TF", name: "French Southern Territories", flag: "🇹🇫" },
  "GA": { code: "GA", name: "Gabon", flag: "🇬🇦" },
  "GM": { code: "GM", name: "Gambia", flag: "🇬🇲" },
  "GE": { code: "GE", name: "Georgia", flag: "🇬🇪" },
  "DE": { code: "DE", name: "Germany", flag: "🇩🇪" },
  "GH": { code: "GH", name: "Ghana", flag: "🇬🇭" },
  "GI": { code: "GI", name: "Gibraltar", flag: "🇬🇮" },
  "GR": { code: "GR", name: "Greece", flag: "🇬🇷" },
  "GL": { code: "GL", name: "Greenland", flag: "🇬🇱" },
  "GD": { code: "GD", name: "Grenada", flag: "🇬🇩" },
  "GP": { code: "GP", name: "Guadeloupe", flag: "🇬🇵" },
  "GU": { code: "GU", name: "Guam", flag: "🇬🇺" },
  "GT": { code: "GT", name: "Guatemala", flag: "🇬🇹" },
  "GG": { code: "GG", name: "Guernsey", flag: "🇬🇬" },
  "GN": { code: "GN", name: "Guinea", flag: "🇬🇳" },
  "GW": { code: "GW", name: "Guinea-Bissau", flag: "🇬🇼" },
  "GY": { code: "GY", name: "Guyana", flag: "🇬🇾" },
  "HT": { code: "HT", name: "Haiti", flag: "🇭🇹" },
  "HN": { code: "HN", name: "Honduras", flag: "🇭🇳" },
  "HK": { code: "HK", name: "Hong Kong SAR China", flag: "🇭🇰" },
  "HU": { code: "HU", name: "Hungary", flag: "🇭🇺" },
  "IS": { code: "IS", name: "Iceland", flag: "🇮🇸" },
  "IN": { code: "IN", name: "India", flag: "🇮🇳" },
  "ID": { code: "ID", name: "Indonesia", flag: "🇮🇩" },
  "IR": { code: "IR", name: "Iran", flag: "🇮🇷" },
  "IQ": { code: "IQ", name: "Iraq", flag: "🇮🇶" },
  "IE": { code: "IE", name: "Ireland", flag: "🇮🇪" },
  "IM": { code: "IM", name: "Isle of Man", flag: "🇮🇲" },
  "IL": { code: "IL", name: "Israel", flag: "🇮🇱" },
  "IT": { code: "IT", name: "Italy", flag: "🇮🇹" },
  "JM": { code: "JM", name: "Jamaica", flag: "🇯🇲" },
  "JP": { code: "JP", name: "Japan", flag: "🇯🇵" },
  "JE": { code: "JE", name: "Jersey", flag: "🇯🇪" },
  "JO": { code: "JO", name: "Jordan", flag: "🇯🇴" },
  "KZ": { code: "KZ", name: "Kazakhstan", flag: "🇰🇿" },
  "KE": { code: "KE", name: "Kenya", flag: "🇰🇪" },
  "KI": { code: "KI", name: "Kiribati", flag: "🇰🇮" },
  "XK": { code: "XK", name: "Kosovo", flag: "🇽🇰" },
  "KW": { code: "KW", name: "Kuwait", flag: "🇰🇼" },
  "KG": { code: "KG", name: "Kyrgyzstan", flag: "🇰🇬" },
  "LA": { code: "LA", name: "Laos", flag: "🇱🇦" },
  "LV": { code: "LV", name: "Latvia", flag: "🇱🇻" },
  "LB": { code: "LB", name: "Lebanon", flag: "🇱🇧" },
  "LS": { code: "LS", name: "Lesotho", flag: "🇱🇸" },
  "LR": { code: "LR", name: "Liberia", flag: "🇱🇷" },
  "LY": { code: "LY", name: "Libya", flag: "🇱🇾" },
  "LI": { code: "LI", name: "Liechtenstein", flag: "🇱🇮" },
  "LT": { code: "LT", name: "Lithuania", flag: "🇱🇹" },
  "LU": { code: "LU", name: "Luxembourg", flag: "🇱🇺" },
  "MO": { code: "MO", name: "Macao SAR China", flag: "🇲🇴" },
  "MG": { code: "MG", name: "Madagascar", flag: "🇲🇬" },
  "MW": { code: "MW", name: "Malawi", flag: "🇲🇼" },
  "MY": { code: "MY", name: "Malaysia", flag: "🇲🇾" },
  "MV": { code: "MV", name: "Maldives", flag: "🇲🇻" },
  "ML": { code: "ML", name: "Mali", flag: "🇲🇱" },
  "MT": { code: "MT", name: "Malta", flag: "🇲🇹" },
  "MH": { code: "MH", name: "Marshall Islands", flag: "🇲🇭" },
  "MQ": { code: "MQ", name: "Martinique", flag: "🇲🇶" },
  "MR": { code: "MR", name: "Mauritania", flag: "🇲🇷" },
  "MU": { code: "MU", name: "Mauritius", flag: "🇲🇺" },
  "YT": { code: "YT", name: "Mayotte", flag: "🇾🇹" },
  "MX": { code: "MX", name: "Mexico", flag: "🇲🇽" },
  "FM": { code: "FM", name: "Micronesia", flag: "🇫🇲" },
  "MD": { code: "MD", name: "Moldova", flag: "🇲🇩" },
  "MC": { code: "MC", name: "Monaco", flag: "🇲🇨" },
  "MN": { code: "MN", name: "Mongolia", flag: "🇲🇳" },
  "ME": { code: "ME", name: "Montenegro", flag: "🇲🇪" },
  "MS": { code: "MS", name: "Montserrat", flag: "🇲🇸" },
  "MA": { code: "MA", name: "Morocco", flag: "🇲🇦" },
  "MZ": { code: "MZ", name: "Mozambique", flag: "🇲🇿" },
  "MM": { code: "MM", name: "Myanmar (Burma)", flag: "🇲🇲" },
  "NA": { code: "NA", name: "Namibia", flag: "🇳🇦" },
  "NR": { code: "NR", name: "Nauru", flag: "🇳🇷" },
  "NP": { code: "NP", name: "Nepal", flag: "🇳🇵" },
  "NL": { code: "NL", name: "Netherlands", flag: "🇳🇱" },
  "NC": { code: "NC", name: "New Caledonia", flag: "🇳🇨" },
  "NZ": { code: "NZ", name: "New Zealand", flag: "🇳🇿" },
  "NI": { code: "NI", name: "Nicaragua", flag: "🇳🇮" },
  "NE": { code: "NE", name: "Niger", flag: "🇳🇪" },
  "NG": { code: "NG", name: "Nigeria", flag: "🇳🇬" },
  "NU": { code: "NU", name: "Niue", flag: "🇳🇺" },
  "NF": { code: "NF", name: "Norfolk Island", flag: "🇳🇫" },
  "KP": { code: "KP", name: "North Korea", flag: "🇰🇵" },
  "MK": { code: "MK", name: "North Macedonia", flag: "🇲🇰" },
  "MP": { code: "MP", name: "Northern Mariana Islands", flag: "🇲🇵" },
  "NO": { code: "NO", name: "Norway", flag: "🇳🇴" },
  "OM": { code: "OM", name: "Oman", flag: "🇴🇲" },
  "PK": { code: "PK", name: "Pakistan", flag: "🇵🇰" },
  "PW": { code: "PW", name: "Palau", flag: "🇵🇼" },
  "PS": { code: "PS", name: "Palestinian Territories", flag: "🇵🇸" },
  "PA": { code: "PA", name: "Panama", flag: "🇵🇦" },
  "PG": { code: "PG", name: "Papua New Guinea", flag: "🇵🇬" },
  "PY": { code: "PY", name: "Paraguay", flag: "🇵🇾" },
  "PE": { code: "PE", name: "Peru", flag: "🇵🇪" },
  "PH": { code: "PH", name: "Philippines", flag: "🇵🇭" },
  "PN": { code: "PN", name: "Pitcairn Islands", flag: "🇵🇳" },
  "PL": { code: "PL", name: "Poland", flag: "🇵🇱" },
  "PT": { code: "PT", name: "Portugal", flag: "🇵🇹" },
  "PR": { code: "PR", name: "Puerto Rico", flag: "🇵🇷" },
  "QA": { code: "QA", name: "Qatar", flag: "🇶🇦" },
  "RE": { code: "RE", name: "Réunion", flag: "🇷🇪" },
  "RO": { code: "RO", name: "Romania", flag: "🇷🇴" },
  "RU": { code: "RU", name: "Russia", flag: "🇷🇺" },
  "RW": { code: "RW", name: "Rwanda", flag: "🇷🇼" },
  "WS": { code: "WS", name: "Samoa", flag: "🇼🇸" },
  "SM": { code: "SM", name: "San Marino", flag: "🇸🇲" },
  "ST": { code: "ST", name: "São Tomé & Príncipe", flag: "🇸🇹" },
  "SA": { code: "SA", name: "Saudi Arabia", flag: "🇸🇦" },
  "SN": { code: "SN", name: "Senegal", flag: "🇸🇳" },
  "RS": { code: "RS", name: "Serbia", flag: "🇷🇸" },
  "SC": { code: "SC", name: "Seychelles", flag: "🇸🇨" },
  "SL": { code: "SL", name: "Sierra Leone", flag: "🇸🇱" },
  "SG": { code: "SG", name: "Singapore", flag: "🇸🇬" },
  "SX": { code: "SX", name: "Sint Maarten", flag: "🇸🇽" },
  "SK": { code: "SK", name: "Slovakia", flag: "🇸🇰" },
  "SI": { code: "SI", name: "Slovenia", flag: "🇸🇮" },
  "SB": { code: "SB", name: "Solomon Islands", flag: "🇸🇧" },
  "SO": { code: "SO", name: "Somalia", flag: "🇸🇴" },
  "ZA": { code: "ZA", name: "South Africa", flag: "🇿🇦" },
  "GS": { code: "GS", name: "South Georgia & South Sandwich Islands", flag: "🇬🇸" },
  "KR": { code: "KR", name: "South Korea", flag: "🇰🇷" },
  "SS": { code: "SS", name: "South Sudan", flag: "🇸🇸" },
  "ES": { code: "ES", name: "Spain", flag: "🇪🇸" },
  "LK": { code: "LK", name: "Sri Lanka", flag: "🇱🇰" },
  "BL": { code: "BL", name: "St. Barthélemy", flag: "🇧🇱" },
  "SH": { code: "SH", name: "St. Helena", flag: "🇸🇭" },
  "KN": { code: "KN", name: "St. Kitts & Nevis", flag: "🇰🇳" },
  "LC": { code: "LC", name: "St. Lucia", flag: "🇱🇨" },
  "MF": { code: "MF", name: "St. Martin", flag: "🇲🇫" },
  "PM": { code: "PM", name: "St. Pierre & Miquelon", flag: "🇵🇲" },
  "VC": { code: "VC", name: "St. Vincent & Grenadines", flag: "🇻🇨" },
  "SD": { code: "SD", name: "Sudan", flag: "🇸🇩" },
  "SR": { code: "SR", name: "Suriname", flag: "🇸🇷" },
  "SJ": { code: "SJ", name: "Svalbard & Jan Mayen", flag: "🇸🇯" },
  "SE": { code: "SE", name: "Sweden", flag: "🇸🇪" },
  "CH": { code: "CH", name: "Switzerland", flag: "🇨🇭" },
  "SY": { code: "SY", name: "Syria", flag: "🇸🇾" },
  "TW": { code: "TW", name: "Taiwan", flag: "🇹🇼" },
  "TJ": { code: "TJ", name: "Tajikistan", flag: "🇹🇯" },
  "TZ": { code: "TZ", name: "Tanzania", flag: "🇹🇿" },
  "TH": { code: "TH", name: "Thailand", flag: "🇹🇭" },
  "TL": { code: "TL", name: "Timor-Leste", flag: "🇹🇱" },
  "TG": { code: "TG", name: "Togo", flag: "🇹🇬" },
  "TO": { code: "TO", name: "Tonga", flag: "🇹🇴" },
  "TT": { code: "TT", name: "Trinidad & Tobago", flag: "🇹🇹" },
  "TN": { code: "TN", name: "Tunisia", flag: "🇹🇳" },
  "TR": { code: "TR", name: "Türkiye", flag: "🇹🇷" },
  "TM": { code: "TM", name: "Turkmenistan", flag: "🇹🇲" },
  "TC": { code: "TC", name: "Turks & Caicos Islands", flag: "🇹🇨" },
  "TV": { code: "TV", name: "Tuvalu", flag: "🇹🇻" },
  "VI": { code: "VI", name: "U.S. Virgin Islands", flag: "🇻🇮" },
  "UG": { code: "UG", name: "Uganda", flag: "🇺🇬" },
  "UA": { code: "UA", name: "Ukraine", flag: "🇺🇦" },
  "AE": { code: "AE", name: "United Arab Emirates", flag: "🇦🇪" },
  "GB": { code: "GB", name: "United Kingdom", flag: "🇬🇧" },
  "US": { code: "US", name: "United States", flag: "🇺🇸" },
  "UY": { code: "UY", name: "Uruguay", flag: "🇺🇾" },
  "UZ": { code: "UZ", name: "Uzbekistan", flag: "🇺🇿" },
  "VU": { code: "VU", name: "Vanuatu", flag: "🇻🇺" },
  "VA": { code: "VA", name: "Vatican City", flag: "🇻🇦" },
  "VE": { code: "VE", name: "Venezuela", flag: "🇻🇪" },
  "VN": { code: "VN", name: "Vietnam", flag: "🇻🇳" },
  "WF": { code: "WF", name: "Wallis & Futuna", flag: "🇼🇫" },
  "EH": { code: "EH", name: "Western Sahara", flag: "🇪🇭" },
  "YE": { code: "YE", name: "Yemen", flag: "🇾🇪" },
  "ZM": { code: "ZM", name: "Zambia", flag: "🇿🇲" },
  "ZW": { code: "ZW", name: "Zimbabwe", flag: "🇿🇼" },
};

export const COUNTRIES_LIST: CountryInfo[] = [
  {
    "code": "AF",
    "name": "Afghanistan",
    "flag": "🇦🇫"
  },
  {
    "code": "AX",
    "name": "Åland Islands",
    "flag": "🇦🇽"
  },
  {
    "code": "AL",
    "name": "Albania",
    "flag": "🇦🇱"
  },
  {
    "code": "DZ",
    "name": "Algeria",
    "flag": "🇩🇿"
  },
  {
    "code": "AS",
    "name": "American Samoa",
    "flag": "🇦🇸"
  },
  {
    "code": "AD",
    "name": "Andorra",
    "flag": "🇦🇩"
  },
  {
    "code": "AO",
    "name": "Angola",
    "flag": "🇦🇴"
  },
  {
    "code": "AI",
    "name": "Anguilla",
    "flag": "🇦🇮"
  },
  {
    "code": "AG",
    "name": "Antigua & Barbuda",
    "flag": "🇦🇬"
  },
  {
    "code": "AR",
    "name": "Argentina",
    "flag": "🇦🇷"
  },
  {
    "code": "AM",
    "name": "Armenia",
    "flag": "🇦🇲"
  },
  {
    "code": "AW",
    "name": "Aruba",
    "flag": "🇦🇼"
  },
  {
    "code": "AU",
    "name": "Australia",
    "flag": "🇦🇺"
  },
  {
    "code": "AT",
    "name": "Austria",
    "flag": "🇦🇹"
  },
  {
    "code": "AZ",
    "name": "Azerbaijan",
    "flag": "🇦🇿"
  },
  {
    "code": "BS",
    "name": "Bahamas",
    "flag": "🇧🇸"
  },
  {
    "code": "BH",
    "name": "Bahrain",
    "flag": "🇧🇭"
  },
  {
    "code": "BD",
    "name": "Bangladesh",
    "flag": "🇧🇩"
  },
  {
    "code": "BB",
    "name": "Barbados",
    "flag": "🇧🇧"
  },
  {
    "code": "BY",
    "name": "Belarus",
    "flag": "🇧🇾"
  },
  {
    "code": "BE",
    "name": "Belgium",
    "flag": "🇧🇪"
  },
  {
    "code": "BZ",
    "name": "Belize",
    "flag": "🇧🇿"
  },
  {
    "code": "BJ",
    "name": "Benin",
    "flag": "🇧🇯"
  },
  {
    "code": "BM",
    "name": "Bermuda",
    "flag": "🇧🇲"
  },
  {
    "code": "BT",
    "name": "Bhutan",
    "flag": "🇧🇹"
  },
  {
    "code": "BO",
    "name": "Bolivia",
    "flag": "🇧🇴"
  },
  {
    "code": "BA",
    "name": "Bosnia & Herzegovina",
    "flag": "🇧🇦"
  },
  {
    "code": "BW",
    "name": "Botswana",
    "flag": "🇧🇼"
  },
  {
    "code": "BR",
    "name": "Brazil",
    "flag": "🇧🇷"
  },
  {
    "code": "VG",
    "name": "British Virgin Islands",
    "flag": "🇻🇬"
  },
  {
    "code": "BN",
    "name": "Brunei",
    "flag": "🇧🇳"
  },
  {
    "code": "BG",
    "name": "Bulgaria",
    "flag": "🇧🇬"
  },
  {
    "code": "BF",
    "name": "Burkina Faso",
    "flag": "🇧🇫"
  },
  {
    "code": "BI",
    "name": "Burundi",
    "flag": "🇧🇮"
  },
  {
    "code": "KH",
    "name": "Cambodia",
    "flag": "🇰🇭"
  },
  {
    "code": "CM",
    "name": "Cameroon",
    "flag": "🇨🇲"
  },
  {
    "code": "CA",
    "name": "Canada",
    "flag": "🇨🇦"
  },
  {
    "code": "CV",
    "name": "Cape Verde",
    "flag": "🇨🇻"
  },
  {
    "code": "BQ",
    "name": "Caribbean Netherlands",
    "flag": "🇧🇶"
  },
  {
    "code": "KY",
    "name": "Cayman Islands",
    "flag": "🇰🇾"
  },
  {
    "code": "CF",
    "name": "Central African Republic",
    "flag": "🇨🇫"
  },
  {
    "code": "TD",
    "name": "Chad",
    "flag": "🇹🇩"
  },
  {
    "code": "CL",
    "name": "Chile",
    "flag": "🇨🇱"
  },
  {
    "code": "CN",
    "name": "China",
    "flag": "🇨🇳"
  },
  {
    "code": "CX",
    "name": "Christmas Island",
    "flag": "🇨🇽"
  },
  {
    "code": "CC",
    "name": "Cocos (Keeling) Islands",
    "flag": "🇨🇨"
  },
  {
    "code": "CO",
    "name": "Colombia",
    "flag": "🇨🇴"
  },
  {
    "code": "KM",
    "name": "Comoros",
    "flag": "🇰🇲"
  },
  {
    "code": "CG",
    "name": "Congo - Brazzaville",
    "flag": "🇨🇬"
  },
  {
    "code": "CD",
    "name": "Congo - Kinshasa",
    "flag": "🇨🇩"
  },
  {
    "code": "CK",
    "name": "Cook Islands",
    "flag": "🇨🇰"
  },
  {
    "code": "CR",
    "name": "Costa Rica",
    "flag": "🇨🇷"
  },
  {
    "code": "CI",
    "name": "Côte d’Ivoire",
    "flag": "🇨🇮"
  },
  {
    "code": "HR",
    "name": "Croatia",
    "flag": "🇭🇷"
  },
  {
    "code": "CU",
    "name": "Cuba",
    "flag": "🇨🇺"
  },
  {
    "code": "CW",
    "name": "Curaçao",
    "flag": "🇨🇼"
  },
  {
    "code": "CY",
    "name": "Cyprus",
    "flag": "🇨🇾"
  },
  {
    "code": "CZ",
    "name": "Czechia",
    "flag": "🇨🇿"
  },
  {
    "code": "DK",
    "name": "Denmark",
    "flag": "🇩🇰"
  },
  {
    "code": "DJ",
    "name": "Djibouti",
    "flag": "🇩🇯"
  },
  {
    "code": "DM",
    "name": "Dominica",
    "flag": "🇩🇲"
  },
  {
    "code": "DO",
    "name": "Dominican Republic",
    "flag": "🇩🇴"
  },
  {
    "code": "EC",
    "name": "Ecuador",
    "flag": "🇪🇨"
  },
  {
    "code": "EG",
    "name": "Egypt",
    "flag": "🇪🇬"
  },
  {
    "code": "SV",
    "name": "El Salvador",
    "flag": "🇸🇻"
  },
  {
    "code": "GQ",
    "name": "Equatorial Guinea",
    "flag": "🇬🇶"
  },
  {
    "code": "ER",
    "name": "Eritrea",
    "flag": "🇪🇷"
  },
  {
    "code": "EE",
    "name": "Estonia",
    "flag": "🇪🇪"
  },
  {
    "code": "SZ",
    "name": "Eswatini",
    "flag": "🇸🇿"
  },
  {
    "code": "ET",
    "name": "Ethiopia",
    "flag": "🇪🇹"
  },
  {
    "code": "FK",
    "name": "Falkland Islands",
    "flag": "🇫🇰"
  },
  {
    "code": "FO",
    "name": "Faroe Islands",
    "flag": "🇫🇴"
  },
  {
    "code": "FJ",
    "name": "Fiji",
    "flag": "🇫🇯"
  },
  {
    "code": "FI",
    "name": "Finland",
    "flag": "🇫🇮"
  },
  {
    "code": "FR",
    "name": "France",
    "flag": "🇫🇷"
  },
  {
    "code": "GF",
    "name": "French Guiana",
    "flag": "🇬🇫"
  },
  {
    "code": "PF",
    "name": "French Polynesia",
    "flag": "🇵🇫"
  },
  {
    "code": "TF",
    "name": "French Southern Territories",
    "flag": "🇹🇫"
  },
  {
    "code": "GA",
    "name": "Gabon",
    "flag": "🇬🇦"
  },
  {
    "code": "GM",
    "name": "Gambia",
    "flag": "🇬🇲"
  },
  {
    "code": "GE",
    "name": "Georgia",
    "flag": "🇬🇪"
  },
  {
    "code": "DE",
    "name": "Germany",
    "flag": "🇩🇪"
  },
  {
    "code": "GH",
    "name": "Ghana",
    "flag": "🇬🇭"
  },
  {
    "code": "GI",
    "name": "Gibraltar",
    "flag": "🇬🇮"
  },
  {
    "code": "GR",
    "name": "Greece",
    "flag": "🇬🇷"
  },
  {
    "code": "GL",
    "name": "Greenland",
    "flag": "🇬🇱"
  },
  {
    "code": "GD",
    "name": "Grenada",
    "flag": "🇬🇩"
  },
  {
    "code": "GP",
    "name": "Guadeloupe",
    "flag": "🇬🇵"
  },
  {
    "code": "GU",
    "name": "Guam",
    "flag": "🇬🇺"
  },
  {
    "code": "GT",
    "name": "Guatemala",
    "flag": "🇬🇹"
  },
  {
    "code": "GG",
    "name": "Guernsey",
    "flag": "🇬🇬"
  },
  {
    "code": "GN",
    "name": "Guinea",
    "flag": "🇬🇳"
  },
  {
    "code": "GW",
    "name": "Guinea-Bissau",
    "flag": "🇬🇼"
  },
  {
    "code": "GY",
    "name": "Guyana",
    "flag": "🇬🇾"
  },
  {
    "code": "HT",
    "name": "Haiti",
    "flag": "🇭🇹"
  },
  {
    "code": "HN",
    "name": "Honduras",
    "flag": "🇭🇳"
  },
  {
    "code": "HK",
    "name": "Hong Kong SAR China",
    "flag": "🇭🇰"
  },
  {
    "code": "HU",
    "name": "Hungary",
    "flag": "🇭🇺"
  },
  {
    "code": "IS",
    "name": "Iceland",
    "flag": "🇮🇸"
  },
  {
    "code": "IN",
    "name": "India",
    "flag": "🇮🇳"
  },
  {
    "code": "ID",
    "name": "Indonesia",
    "flag": "🇮🇩"
  },
  {
    "code": "IR",
    "name": "Iran",
    "flag": "🇮🇷"
  },
  {
    "code": "IQ",
    "name": "Iraq",
    "flag": "🇮🇶"
  },
  {
    "code": "IE",
    "name": "Ireland",
    "flag": "🇮🇪"
  },
  {
    "code": "IM",
    "name": "Isle of Man",
    "flag": "🇮🇲"
  },
  {
    "code": "IL",
    "name": "Israel",
    "flag": "🇮🇱"
  },
  {
    "code": "IT",
    "name": "Italy",
    "flag": "🇮🇹"
  },
  {
    "code": "JM",
    "name": "Jamaica",
    "flag": "🇯🇲"
  },
  {
    "code": "JP",
    "name": "Japan",
    "flag": "🇯🇵"
  },
  {
    "code": "JE",
    "name": "Jersey",
    "flag": "🇯🇪"
  },
  {
    "code": "JO",
    "name": "Jordan",
    "flag": "🇯🇴"
  },
  {
    "code": "KZ",
    "name": "Kazakhstan",
    "flag": "🇰🇿"
  },
  {
    "code": "KE",
    "name": "Kenya",
    "flag": "🇰🇪"
  },
  {
    "code": "KI",
    "name": "Kiribati",
    "flag": "🇰🇮"
  },
  {
    "code": "XK",
    "name": "Kosovo",
    "flag": "🇽🇰"
  },
  {
    "code": "KW",
    "name": "Kuwait",
    "flag": "🇰🇼"
  },
  {
    "code": "KG",
    "name": "Kyrgyzstan",
    "flag": "🇰🇬"
  },
  {
    "code": "LA",
    "name": "Laos",
    "flag": "🇱🇦"
  },
  {
    "code": "LV",
    "name": "Latvia",
    "flag": "🇱🇻"
  },
  {
    "code": "LB",
    "name": "Lebanon",
    "flag": "🇱🇧"
  },
  {
    "code": "LS",
    "name": "Lesotho",
    "flag": "🇱🇸"
  },
  {
    "code": "LR",
    "name": "Liberia",
    "flag": "🇱🇷"
  },
  {
    "code": "LY",
    "name": "Libya",
    "flag": "🇱🇾"
  },
  {
    "code": "LI",
    "name": "Liechtenstein",
    "flag": "🇱🇮"
  },
  {
    "code": "LT",
    "name": "Lithuania",
    "flag": "🇱🇹"
  },
  {
    "code": "LU",
    "name": "Luxembourg",
    "flag": "🇱🇺"
  },
  {
    "code": "MO",
    "name": "Macao SAR China",
    "flag": "🇲🇴"
  },
  {
    "code": "MG",
    "name": "Madagascar",
    "flag": "🇲🇬"
  },
  {
    "code": "MW",
    "name": "Malawi",
    "flag": "🇲🇼"
  },
  {
    "code": "MY",
    "name": "Malaysia",
    "flag": "🇲🇾"
  },
  {
    "code": "MV",
    "name": "Maldives",
    "flag": "🇲🇻"
  },
  {
    "code": "ML",
    "name": "Mali",
    "flag": "🇲🇱"
  },
  {
    "code": "MT",
    "name": "Malta",
    "flag": "🇲🇹"
  },
  {
    "code": "MH",
    "name": "Marshall Islands",
    "flag": "🇲🇭"
  },
  {
    "code": "MQ",
    "name": "Martinique",
    "flag": "🇲🇶"
  },
  {
    "code": "MR",
    "name": "Mauritania",
    "flag": "🇲🇷"
  },
  {
    "code": "MU",
    "name": "Mauritius",
    "flag": "🇲🇺"
  },
  {
    "code": "YT",
    "name": "Mayotte",
    "flag": "🇾🇹"
  },
  {
    "code": "MX",
    "name": "Mexico",
    "flag": "🇲🇽"
  },
  {
    "code": "FM",
    "name": "Micronesia",
    "flag": "🇫🇲"
  },
  {
    "code": "MD",
    "name": "Moldova",
    "flag": "🇲🇩"
  },
  {
    "code": "MC",
    "name": "Monaco",
    "flag": "🇲🇨"
  },
  {
    "code": "MN",
    "name": "Mongolia",
    "flag": "🇲🇳"
  },
  {
    "code": "ME",
    "name": "Montenegro",
    "flag": "🇲🇪"
  },
  {
    "code": "MS",
    "name": "Montserrat",
    "flag": "🇲🇸"
  },
  {
    "code": "MA",
    "name": "Morocco",
    "flag": "🇲🇦"
  },
  {
    "code": "MZ",
    "name": "Mozambique",
    "flag": "🇲🇿"
  },
  {
    "code": "MM",
    "name": "Myanmar (Burma)",
    "flag": "🇲🇲"
  },
  {
    "code": "NA",
    "name": "Namibia",
    "flag": "🇳🇦"
  },
  {
    "code": "NR",
    "name": "Nauru",
    "flag": "🇳🇷"
  },
  {
    "code": "NP",
    "name": "Nepal",
    "flag": "🇳🇵"
  },
  {
    "code": "NL",
    "name": "Netherlands",
    "flag": "🇳🇱"
  },
  {
    "code": "NC",
    "name": "New Caledonia",
    "flag": "🇳🇨"
  },
  {
    "code": "NZ",
    "name": "New Zealand",
    "flag": "🇳🇿"
  },
  {
    "code": "NI",
    "name": "Nicaragua",
    "flag": "🇳🇮"
  },
  {
    "code": "NE",
    "name": "Niger",
    "flag": "🇳🇪"
  },
  {
    "code": "NG",
    "name": "Nigeria",
    "flag": "🇳🇬"
  },
  {
    "code": "NU",
    "name": "Niue",
    "flag": "🇳🇺"
  },
  {
    "code": "NF",
    "name": "Norfolk Island",
    "flag": "🇳🇫"
  },
  {
    "code": "KP",
    "name": "North Korea",
    "flag": "🇰🇵"
  },
  {
    "code": "MK",
    "name": "North Macedonia",
    "flag": "🇲🇰"
  },
  {
    "code": "MP",
    "name": "Northern Mariana Islands",
    "flag": "🇲🇵"
  },
  {
    "code": "NO",
    "name": "Norway",
    "flag": "🇳🇴"
  },
  {
    "code": "OM",
    "name": "Oman",
    "flag": "🇴🇲"
  },
  {
    "code": "PK",
    "name": "Pakistan",
    "flag": "🇵🇰"
  },
  {
    "code": "PW",
    "name": "Palau",
    "flag": "🇵🇼"
  },
  {
    "code": "PS",
    "name": "Palestinian Territories",
    "flag": "🇵🇸"
  },
  {
    "code": "PA",
    "name": "Panama",
    "flag": "🇵🇦"
  },
  {
    "code": "PG",
    "name": "Papua New Guinea",
    "flag": "🇵🇬"
  },
  {
    "code": "PY",
    "name": "Paraguay",
    "flag": "🇵🇾"
  },
  {
    "code": "PE",
    "name": "Peru",
    "flag": "🇵🇪"
  },
  {
    "code": "PH",
    "name": "Philippines",
    "flag": "🇵🇭"
  },
  {
    "code": "PN",
    "name": "Pitcairn Islands",
    "flag": "🇵🇳"
  },
  {
    "code": "PL",
    "name": "Poland",
    "flag": "🇵🇱"
  },
  {
    "code": "PT",
    "name": "Portugal",
    "flag": "🇵🇹"
  },
  {
    "code": "PR",
    "name": "Puerto Rico",
    "flag": "🇵🇷"
  },
  {
    "code": "QA",
    "name": "Qatar",
    "flag": "🇶🇦"
  },
  {
    "code": "RE",
    "name": "Réunion",
    "flag": "🇷🇪"
  },
  {
    "code": "RO",
    "name": "Romania",
    "flag": "🇷🇴"
  },
  {
    "code": "RU",
    "name": "Russia",
    "flag": "🇷🇺"
  },
  {
    "code": "RW",
    "name": "Rwanda",
    "flag": "🇷🇼"
  },
  {
    "code": "WS",
    "name": "Samoa",
    "flag": "🇼🇸"
  },
  {
    "code": "SM",
    "name": "San Marino",
    "flag": "🇸🇲"
  },
  {
    "code": "ST",
    "name": "São Tomé & Príncipe",
    "flag": "🇸🇹"
  },
  {
    "code": "SA",
    "name": "Saudi Arabia",
    "flag": "🇸🇦"
  },
  {
    "code": "SN",
    "name": "Senegal",
    "flag": "🇸🇳"
  },
  {
    "code": "RS",
    "name": "Serbia",
    "flag": "🇷🇸"
  },
  {
    "code": "SC",
    "name": "Seychelles",
    "flag": "🇸🇨"
  },
  {
    "code": "SL",
    "name": "Sierra Leone",
    "flag": "🇸🇱"
  },
  {
    "code": "SG",
    "name": "Singapore",
    "flag": "🇸🇬"
  },
  {
    "code": "SX",
    "name": "Sint Maarten",
    "flag": "🇸🇽"
  },
  {
    "code": "SK",
    "name": "Slovakia",
    "flag": "🇸🇰"
  },
  {
    "code": "SI",
    "name": "Slovenia",
    "flag": "🇸🇮"
  },
  {
    "code": "SB",
    "name": "Solomon Islands",
    "flag": "🇸🇧"
  },
  {
    "code": "SO",
    "name": "Somalia",
    "flag": "🇸🇴"
  },
  {
    "code": "ZA",
    "name": "South Africa",
    "flag": "🇿🇦"
  },
  {
    "code": "GS",
    "name": "South Georgia & South Sandwich Islands",
    "flag": "🇬🇸"
  },
  {
    "code": "KR",
    "name": "South Korea",
    "flag": "🇰🇷"
  },
  {
    "code": "SS",
    "name": "South Sudan",
    "flag": "🇸🇸"
  },
  {
    "code": "ES",
    "name": "Spain",
    "flag": "🇪🇸"
  },
  {
    "code": "LK",
    "name": "Sri Lanka",
    "flag": "🇱🇰"
  },
  {
    "code": "BL",
    "name": "St. Barthélemy",
    "flag": "🇧🇱"
  },
  {
    "code": "SH",
    "name": "St. Helena",
    "flag": "🇸🇭"
  },
  {
    "code": "KN",
    "name": "St. Kitts & Nevis",
    "flag": "🇰🇳"
  },
  {
    "code": "LC",
    "name": "St. Lucia",
    "flag": "🇱🇨"
  },
  {
    "code": "MF",
    "name": "St. Martin",
    "flag": "🇲🇫"
  },
  {
    "code": "PM",
    "name": "St. Pierre & Miquelon",
    "flag": "🇵🇲"
  },
  {
    "code": "VC",
    "name": "St. Vincent & Grenadines",
    "flag": "🇻🇨"
  },
  {
    "code": "SD",
    "name": "Sudan",
    "flag": "🇸🇩"
  },
  {
    "code": "SR",
    "name": "Suriname",
    "flag": "🇸🇷"
  },
  {
    "code": "SJ",
    "name": "Svalbard & Jan Mayen",
    "flag": "🇸🇯"
  },
  {
    "code": "SE",
    "name": "Sweden",
    "flag": "🇸🇪"
  },
  {
    "code": "CH",
    "name": "Switzerland",
    "flag": "🇨🇭"
  },
  {
    "code": "SY",
    "name": "Syria",
    "flag": "🇸🇾"
  },
  {
    "code": "TW",
    "name": "Taiwan",
    "flag": "🇹🇼"
  },
  {
    "code": "TJ",
    "name": "Tajikistan",
    "flag": "🇹🇯"
  },
  {
    "code": "TZ",
    "name": "Tanzania",
    "flag": "🇹🇿"
  },
  {
    "code": "TH",
    "name": "Thailand",
    "flag": "🇹🇭"
  },
  {
    "code": "TL",
    "name": "Timor-Leste",
    "flag": "🇹🇱"
  },
  {
    "code": "TG",
    "name": "Togo",
    "flag": "🇹🇬"
  },
  {
    "code": "TO",
    "name": "Tonga",
    "flag": "🇹🇴"
  },
  {
    "code": "TT",
    "name": "Trinidad & Tobago",
    "flag": "🇹🇹"
  },
  {
    "code": "TN",
    "name": "Tunisia",
    "flag": "🇹🇳"
  },
  {
    "code": "TR",
    "name": "Türkiye",
    "flag": "🇹🇷"
  },
  {
    "code": "TM",
    "name": "Turkmenistan",
    "flag": "🇹🇲"
  },
  {
    "code": "TC",
    "name": "Turks & Caicos Islands",
    "flag": "🇹🇨"
  },
  {
    "code": "TV",
    "name": "Tuvalu",
    "flag": "🇹🇻"
  },
  {
    "code": "VI",
    "name": "U.S. Virgin Islands",
    "flag": "🇻🇮"
  },
  {
    "code": "UG",
    "name": "Uganda",
    "flag": "🇺🇬"
  },
  {
    "code": "UA",
    "name": "Ukraine",
    "flag": "🇺🇦"
  },
  {
    "code": "AE",
    "name": "United Arab Emirates",
    "flag": "🇦🇪"
  },
  {
    "code": "GB",
    "name": "United Kingdom",
    "flag": "🇬🇧"
  },
  {
    "code": "US",
    "name": "United States",
    "flag": "🇺🇸"
  },
  {
    "code": "UY",
    "name": "Uruguay",
    "flag": "🇺🇾"
  },
  {
    "code": "UZ",
    "name": "Uzbekistan",
    "flag": "🇺🇿"
  },
  {
    "code": "VU",
    "name": "Vanuatu",
    "flag": "🇻🇺"
  },
  {
    "code": "VA",
    "name": "Vatican City",
    "flag": "🇻🇦"
  },
  {
    "code": "VE",
    "name": "Venezuela",
    "flag": "🇻🇪"
  },
  {
    "code": "VN",
    "name": "Vietnam",
    "flag": "🇻🇳"
  },
  {
    "code": "WF",
    "name": "Wallis & Futuna",
    "flag": "🇼🇫"
  },
  {
    "code": "EH",
    "name": "Western Sahara",
    "flag": "🇪🇭"
  },
  {
    "code": "YE",
    "name": "Yemen",
    "flag": "🇾🇪"
  },
  {
    "code": "ZM",
    "name": "Zambia",
    "flag": "🇿🇲"
  },
  {
    "code": "ZW",
    "name": "Zimbabwe",
    "flag": "🇿🇼"
  }
];
