/** @jsxImportSource solid-js */
import { createSignal } from "solid-js";
import {
  fetchFollows,
  followSource,
  unfollowSource,
  type FollowedSource,
} from "./api";

/**
 * useFollows — tracks which sources the current device follows.
 *
 * State is shared across ALL calls to useFollows() in the same
 * page. We use a module-level signal pair (not Solid context)
 * so that nested components like FollowButton see the same
 * state as the top-level App without needing to plumb props
 * or wrap everything in a provider.
 *
 * The server's D1 `source_follows` table is the source of truth.
 * Local state is a cache hydrated from the server on first
 * mount, then updated optimistically on follow/unfollow.
 *
 * Until we have real auth, "the current device" is identified
 * by a UUID generated by `getAntenaDeviceId()` (stored in
 * localStorage).
 */

// Module-level state — shared across all useFollows() callers.
const [follows, setFollows] = createSignal<FollowedSource[]>([]);
const [loaded, setLoaded] = createSignal(false);

/**
 * Reset the shared follows state. Intended for tests — production
 * code should never call this (the state is hydrated from the
 * server exactly once at startup).
 */
export function __resetFollowsForTests(): void {
  setFollows([]);
  setLoaded(false);
  hydrationStarted = false;
}

// Hydrate from server exactly once (subsequent useFollows()
// calls reuse the same hydrated state). The singleton pattern
// means we never re-fetch on remount.
let hydrationStarted = false;
function ensureHydrated() {
  if (hydrationStarted) return;
  hydrationStarted = true;
  void (async () => {
    const initial = await fetchFollows();
    setFollows(initial);
    setLoaded(true);
  })();
}

export function useFollows() {
  ensureHydrated();

  const followedIds = (): Set<number> =>
    new Set(follows().map((f) => f.sourceId));

  const isFollowing = (sourceId: number): boolean =>
    followedIds().has(sourceId);

  const follow = async (sourceId: number): Promise<boolean> => {
    const ok = await followSource(sourceId);
    if (ok) {
      setFollows((prev) => {
        if (prev.some((f) => f.sourceId === sourceId)) return prev;
        return [
          ...prev,
          {
            sourceId,
            sourceName: null,
            sourceUrl: null,
            sourceDomain: null,
            createdAt: new Date().toISOString(),
          },
        ];
      });
    }
    return ok;
  };

  const unfollow = async (sourceId: number): Promise<boolean> => {
    const ok = await unfollowSource(sourceId);
    if (ok) {
      setFollows((prev) => prev.filter((f) => f.sourceId !== sourceId));
    }
    return ok;
  };

  const toggle = async (sourceId: number): Promise<boolean> => {
    return isFollowing(sourceId) ? unfollow(sourceId) : follow(sourceId);
  };

  /** Force a re-fetch from the server. Used after onboarding
   *  where multiple sources are followed in quick succession
   *  via the API directly (not via the follow() helper) — we
   *  need to pull the actual server state so the "Siguiendo"
   *  tab works immediately. */
  const refresh = async (): Promise<void> => {
    const next = await fetchFollows();
    setFollows(next);
  };

  return {
    follows,
    followedIds,
    isFollowing,
    follow,
    unfollow,
    toggle,
    refresh,
    loaded,
  };
}
