/** @jsxImportSource solid-js */
import { createSignal, createEffect } from "solid-js";
import {
  fetchFollows,
  followSource,
  unfollowSource,
  type FollowedSource,
} from "./api";

/**
 * useFollows — tracks which sources the current device follows.
 *
 * State is the union of (a) the local Set of source ids (kept in
 * a signal so the UI can react) and (b) a sync with the server's
 * D1 `source_follows` table. The server is the source of truth —
 * the local state is just a cache hydrated from the server on
 * mount and updated optimistically on follow/unfollow.
 *
 * Until we have real auth, "the current device" is identified by
 * a UUID generated by `getAntenaDeviceId()` (stored in
 * localStorage).
 */
export function useFollows() {
  const [follows, setFollows] = createSignal<FollowedSource[]>([]);
  const [loaded, setLoaded] = createSignal(false);

  // Hydrate from server on mount.
  void (async () => {
    const initial = await fetchFollows();
    setFollows(initial);
    setLoaded(true);
  })();

  const followedIds = (): Set<number> =>
    new Set(follows().map((f) => f.sourceId));

  const isFollowing = (sourceId: number): boolean =>
    followedIds().has(sourceId);

  const follow = async (sourceId: number): Promise<boolean> => {
    // Optimistic update.
    const ok = await followSource(sourceId);
    if (ok) {
      setFollows((prev) => {
        if (prev.some((f) => f.sourceId === sourceId)) return prev;
        return [
          ...prev,
          {
            sourceId,
            sourceName: null,
            sourceUrl: null,
            sourceDomain: null,
            createdAt: new Date().toISOString(),
          },
        ];
      });
    }
    return ok;
  };

  const unfollow = async (sourceId: number): Promise<boolean> => {
    const ok = await unfollowSource(sourceId);
    if (ok) {
      setFollows((prev) => prev.filter((f) => f.sourceId !== sourceId));
    }
    return ok;
  };

  const toggle = async (sourceId: number): Promise<boolean> => {
    return isFollowing(sourceId) ? unfollow(sourceId) : follow(sourceId);
  };

  return {
    follows,
    followedIds,
    isFollowing,
    follow,
    unfollow,
    toggle,
    loaded,
  };
}
