#!/usr/bin/env node
/**
 * Generates src/lib/countries.ts from random-radio's worldcities.csv.
 * Extracts distinct (country_code, country_name) pairs.
 *
 * Output: ~216 countries with ISO-2 code, name, flag emoji.
 *
 * Run: pnpm generate:countries
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SOURCE = '/Users/omatic/proyectos/random-radio/crawler/data/worldcities.csv';
const OUTPUT = resolve(__dirname, '../src/lib/countries.ts');

interface Row {
  code: string;
  name: string;
  flag: string;
}

function countryCodeToFlag(code: string): string {
  if (!/^[A-Z]{2}$/.test(code)) return '🌍';
  const base = 0x1f1e6;
  const A = 0x41;
  return String.fromCodePoint(
    base + (code.charCodeAt(0) - A),
    base + (code.charCodeAt(1) - A),
  );
}

function countryNameFor(code: string): string {
  try {
    const dn = new Intl.DisplayNames(['en'], { type: 'region' });
    return dn.of(code) || code;
  } catch {
    return code;
  }
}

function main(): void {
  const raw = readFileSync(SOURCE, 'utf-8');
  const lines = raw.split('\n').slice(1); // skip header

  const seen = new Set<string>(); // distinct ISO codes
  for (const line of lines) {
    const cols = line.split(',');
    if (cols.length < 1) continue;
    const code = cols[0];
    if (!/^[A-Z]{2}$/.test(code)) continue;
    seen.add(code);
  }

  const countries: Row[] = Array.from(seen)
    .map((code) => ({
      code,
      name: countryNameFor(code),
      flag: countryCodeToFlag(code),
    }))
    .sort((a, b) => a.name.localeCompare(b.name));

  const content = `// AUTO-GENERATED by scripts/generate-countries.ts — do not edit.
export interface CountryInfo {
  code: string;
  name: string;
  flag: string;
}

export const COUNTRIES: Record<string, CountryInfo> = {
${countries.map((c) => `  "${c.code}": { code: "${c.code}", name: ${JSON.stringify(c.name)}, flag: "${c.flag}" },`).join('\n')}
};

export const COUNTRIES_LIST: CountryInfo[] = ${JSON.stringify(countries, null, 2)};
`;

  writeFileSync(OUTPUT, content, 'utf-8');
  console.log(`Wrote ${countries.length} countries to ${OUTPUT}`);
}

main();