import { Hono } from "hono";
import type { Env } from "../lib/types";
import { authMiddleware } from "../middleware/auth";

export const codegenRoutes = new Hono<{ Bindings: Env }>();

/**
 * GET /api/extract/codegen/:sourceId
 * 
 * Returns site HTML structure for Hermes to analyze
 * and potentially generate custom extraction code
 */
codegenRoutes.get("/codegen/:sourceId", authMiddleware, async (c) => {
  const sourceId = parseInt(c.req.param("sourceId"));
  const db = c.env.DB;
  
  // Get source info
  const source = await db.prepare(
    "SELECT * FROM sources WHERE id = ?"
  ).bind(sourceId).first<any>();

  if (!source) {
    return c.json({ error: "Source not found" }, 404);
  }

  // Fetch page HTML (sample)
  try {
    const controller = new AbortController();
    setTimeout(() => controller.abort(), 15000);

    const response = await fetch(source.url, {
      signal: controller.signal,
      headers: {
        'User-Agent': 'Mozilla/5.0 (compatible; AKIRA/1.0)',
        'Accept': 'text/html'
      }
    });

    const html = await response.text();
    
    // Extract patterns for analysis
    const patterns = {
      has_rss: html.includes('/feed') || html.includes('/rss') || html.includes('atom.xml'),
      has_wordpress: html.includes('wp-content') || html.includes('wp-json'),
      has_joomla: html.includes('joomla') || html.includes('com_content'),
      article_patterns: extractPatterns(html),
      meta_info: {
        title: html.match(/<title>(.*?)<\/title>/)?.[1] || '',
        generator: html.match(/<meta name="generator" content="(.*?)"/)?.[1] || '',
        og_type: html.match(/<meta property="og:type" content="(.*?)"/)?.[1] || ''
      }
    };

    return c.json({
      source: {
        id: source.id,
        name: source.name,
        url: source.url,
        type: source.type
      },
      html_sample: html.slice(0, 5000), // First 5KB for analysis
      patterns,
      suggestions: generateSuggestions(patterns),
      extraction_hints: {
        possible_article_selectors: findArticleSelectors(html),
        possible_title_selectors: findTitleSelectors(html),
        possible_date_selectors: findDateSelectors(html)
      }
    });

  } catch (error) {
    return c.json({ 
      error: "Failed to fetch site",
      message: (error as Error).message 
    }, 500);
  }
});

/**
 * POST /api/extract/codegen/run
 * 
 * Run custom extraction code generated by Hermes
 */
codegenRoutes.post("/codegen/run", authMiddleware, async (c) => {
  const { url, extractor_code, source_id } = await c.req.json();
  
  if (!url || !extractor_code) {
    return c.json({ error: "Missing url or extractor_code" }, 400);
  }

  // Create temp file with extractor code
  const tempPath = `/tmp/extractor_${Date.now()}.js`;
  
  try {
    // Write extractor code to temp file
    // Note: In Cloudflare Workers, we can't write files
    // Instead, we'll evaluate the code using a sandbox
    
    // For now, return instructions for Hermes to run locally
    return c.json({
      status: "pending_execution",
      message: "Code must be executed by Hermes agent locally",
      code: extractor_code,
      url: url,
      execution_command: `node -e "${extractor_code.replace(/"/g, '\\"')}" "${url}"`,
      source_id: source_id
    });

  } catch (error) {
    return c.json({ 
      error: "Execution failed",
      message: (error as Error).message 
    }, 500);
  }
});

// ============================================
// HELPER FUNCTIONS
// ============================================

function extractPatterns(html: string): string[] {
  const patterns: string[] = [];
  
  // Check for common article containers
  const containerPatterns = [
    /class="[^"]*(?:article|post|nota|noticia|news|entry)[^"]*"/gi,
    /<article[^>]*>/gi,
    /class="[^"]*(?:card|item)[^"]*"[^>]*>/gi
  ];
  
  for (const pattern of containerPatterns) {
    const matches = html.match(pattern);
    if (matches) {
      patterns.push(...matches.slice(0, 3));
    }
  }
  
  return [...new Set(patterns)].slice(0, 10);
}

function generateSuggestions(patterns: any): string[] {
  const suggestions: string[] = [];
  
  if (patterns.has_rss) {
    suggestions.push("✅ RSS feed detected - use standard RSS extraction");
  }
  
  if (patterns.has_wordpress) {
    suggestions.push("✅ WordPress detected - use WP REST API");
  }
  
  if (patterns.has_joomla) {
    suggestions.push("⚠️ Joomla detected - may need custom parser");
  }
  
  if (patterns.article_patterns.length > 0) {
    suggestions.push(`Found ${patterns.article_patterns.length} article patterns`);
    suggestions.push(`Try selector: ${patterns.article_patterns[0]}`);
  }
  
  if (patterns.meta_info.generator) {
    suggestions.push(`CMS: ${patterns.meta_info.generator}`);
  }
  
  if (suggestions.length === 0) {
    suggestions.push("⚠️ Unknown CMS - custom code generation may be needed");
  }
  
  return suggestions;
}

function findArticleSelectors(html: string): string[] {
  const selectors: string[] = [];
  const patterns = [
    /<article[^>]*class="([^"]*)"[^>]*>/gi,
    /<div[^>]*class="[^"]*(?:article|post|nota|noticia)[^"]*"[^>]*>/gi,
    /<div[^>]*class="[^"]*card[^"]*"[^>]*>/gi
  ];
  
  for (const pattern of patterns) {
    let match;
    while ((match = pattern.exec(html)) !== null) {
      if (match[0].length < 200) {
        selectors.push(match[0].slice(0, 100));
      }
    }
  }
  
  return [...new Set(selectors)].slice(0, 5);
}

function findTitleSelectors(html: string): string[] {
  const selectors: string[] = [];
  const patterns = [
    /<h[12][^>]*class="([^"]*)"[^>]*>/gi,
    /<a[^>]*class="[^"]*(?:title|headline)[^"]*"[^>]*>/gi
  ];
  
  for (const pattern of patterns) {
    let match;
    while ((match = pattern.exec(html)) !== null) {
      if (match[0].length < 150) {
        selectors.push(match[0].slice(0, 100));
      }
    }
  }
  
  return [...new Set(selectors)].slice(0, 5);
}

function findDateSelectors(html: string): string[] {
  const selectors: string[] = [];
  const patterns = [
    /<time[^>]*>/gi,
    /<span[^>]*class="[^"]*(?:date|time|fecha)[^"]*"[^>]*>/gi,
    /<meta[^>]*property="article:published_time"[^>]*>/gi
  ];
  
  for (const pattern of patterns) {
    let match;
    while ((match = pattern.exec(html)) !== null) {
      selectors.push(match[0].slice(0, 100));
    }
  }
  
  return [...new Set(selectors)].slice(0, 5);
}
