import { Hono } from "hono";
import type { Env } from "../lib/types";

export const faqRoutes = new Hono<{ Bindings: Env }>();

// GET /api/clusters/:id/faqs
//
// Returns the JSON array of reader-style Q&A pairs generated by the
// AKIRA FAQ generator (core/faq_generator.py). The payload is stored
// on `clusters.faqs_json` and is regenerated every time synthesis
// runs for the cluster (mirrors /contradictions and /bias-narrative).
//
// Response shape:
//   {
//     cluster_id: "...",
//     faqs: [
//       { question: "¿...?", answer: "...", source_count: N },
//       ...
//     ],
//     count: 3,
//     stored_count: 3,
//     generated_at: "2026-07-12T..."
//   }
//
// 200 with empty array if synthesis hasn't run yet for this cluster.
// 200 with count=0 if synthesis ran but found nothing to extract.
faqRoutes.get("/:id/faqs", async (c) => {
  const clusterId = c.req.param("id");
  if (!clusterId) return c.json({ error: "cluster id required" }, 400);

  const row = await c.env.DB
    .prepare(
      "SELECT faqs_json, faqs_at, faqs_count " +
      "FROM clusters WHERE id = ?"
    )
    .bind(clusterId)
    .first<{
      faqs_json: string | null;
      faqs_at: string | null;
      faqs_count: number | null;
    }>();

  if (!row) {
    return c.json({ error: "cluster not found" }, 404);
  }

  let faqs: unknown[] = [];
  if (row.faqs_json) {
    try {
      const parsed = JSON.parse(row.faqs_json);
      if (Array.isArray(parsed)) {
        faqs = parsed;
      }
    } catch {
      // Corrupt JSON — return empty array instead of 500. The next
      // synthesis run will overwrite the bad value.
      faqs = [];
    }
  }

  return c.json({
    cluster_id: clusterId,
    faqs,
    count: faqs.length,
    stored_count: row.faqs_count ?? 0,
    generated_at: row.faqs_at,
  }, {
    headers: {
      // Edge cache: 60s fresh, 24h SWR. FAQs regenerate only when
      // synthesis runs, so the freshness window is generous.
      "Cache-Control": "public, s-maxage=60, stale-while-revalidate=86400",
    },
  });
});