#!/usr/bin/env python3
"""
Pure-clustering baseline — measures cluster quality WITHOUT
requiring LM Studio. Useful when the embedding model is
overloaded or unavailable.

This is the FIRST measurement of cluster quality for the
golden set, with NO LLM cost. It only needs the local SQLite.

What it measures:
  For each cluster in the golden set:
    - cluster_size: how many cards the v2 clusterer assigned
    - n_relevant_in_cluster: how many of those are golden-relevant
    - n_irrelevant_in_cluster: how many are golden-irrelevant
    - precision: relevant / (relevant + irrelevant)

The relevant cards are ALL in their cluster (recall = 1.0)
because the cluster_id was generated by the algorithm that
already grouped them. The interesting metric is PRECISION:
of the cards in this cluster, what % are actually relevant?

This is essentially the "noise ratio" of each cluster. A
perfect cluster has 1.0 precision. A bad cluster (like Darthés
at 0.32) has 2/3 of its cards being noise.
"""

import argparse
import json
import os
import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
AKIRA_ROOT = HERE.parent


def load_golden(path: str):
    clusters = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                clusters.append(json.loads(line))
            except json.JSONDecodeError as e:
                print(f"WARN: invalid JSON: {e}", file=sys.stderr)
    return clusters


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--golden", default=str(AKIRA_ROOT / "data" / "golden_set.jsonl"))
    ap.add_argument("--db", default=str(AKIRA_ROOT / "data" / "akira.db"))
    ap.add_argument("--output", default=None)
    args = ap.parse_args()

    golden = load_golden(args.golden)
    if not golden:
        print("ERROR: empty golden set", file=sys.stderr)
        sys.exit(1)

    with sqlite3.connect(args.db) as conn:
        per_cluster = []
        total_relevant = 0
        total_relevant_in_cluster = 0
        total_irrelevant = 0
        total_irrelevant_in_cluster = 0
        for cluster in golden:
            cid = cluster["cluster_id"]
            label = cluster.get("label", cid)
            relevant_ids = {c["id"] for c in cluster["cards"] if c.get("relevant")}
            irrelevant_ids = {c["id"] for c in cluster["cards"] if not c.get("relevant")}
            all_golden_ids = list(relevant_ids | irrelevant_ids)
            if not all_golden_ids:
                continue
            placeholders = ",".join("?" * len(all_golden_ids))
            rows = conn.execute(
                f"SELECT id, cluster_id FROM news_cards WHERE id IN ({placeholders})",
                all_golden_ids,
            ).fetchall()
            rel_in = sum(1 for cid_db, c_cl in rows if cid_db in relevant_ids and c_cl == cid)
            rel_out = sum(1 for cid_db, c_cl in rows if cid_db in relevant_ids and c_cl != cid)
            irrel_in = sum(1 for cid_db, c_cl in rows if cid_db in irrelevant_ids and c_cl == cid)
            irrel_out = sum(1 for cid_db, c_cl in rows if cid_db in irrelevant_ids and c_cl != cid)
            cluster_size = conn.execute(
                "SELECT COUNT(*) FROM news_cards WHERE cluster_id=?", (cid,)
            ).fetchone()[0]
            precision = rel_in / (rel_in + irrel_in) if (rel_in + irrel_in) > 0 else 0
            recall = rel_in / (rel_in + rel_out) if (rel_in + rel_out) > 0 else 0
            total_relevant += len(relevant_ids)
            total_relevant_in_cluster += rel_in
            total_irrelevant += len(irrelevant_ids)
            total_irrelevant_in_cluster += irrel_in
            per_cluster.append({
                "cluster_id": cid,
                "label": label,
                "cluster_size": cluster_size,
                "n_relevant_in_cluster": rel_in,
                "n_relevant_elsewhere": rel_out,
                "n_irrelevant_in_cluster": irrel_in,
                "n_irrelevant_elsewhere": irrel_out,
                "precision": round(precision, 3),
                "recall": round(recall, 3),
            })
            print(
                f"  {label[:50]:<50} cluster_size={cluster_size:>3}, "
                f"rel_in={rel_in:>2}, irrel_in={irrel_in:>2}, "
                f"precision={precision:.2f}, recall={recall:.2f}"
            )
        overall_p = total_relevant_in_cluster / max(
            total_relevant_in_cluster + total_irrelevant_in_cluster, 1
        )
        overall_r = total_relevant_in_cluster / max(total_relevant, 1)
        print()
        print(f"=== TOTALS ===")
        print(f"  overall precision: {overall_p:.3f}  (target: ≥ 0.85 for clean clusters)")
        print(f"  overall recall:    {overall_r:.3f}  (target: 1.00)")
        print(
            f"  ratio:             {total_relevant_in_cluster}:{total_irrelevant_in_cluster} "
            f"(relevant:irrelevant in cluster)"
        )

    out_dir = AKIRA_ROOT / ".reports"
    out_dir.mkdir(exist_ok=True)
    out_path = Path(args.output) if args.output else (
        out_dir / f"cluster-baseline-{datetime.now(timezone.utc).strftime('%Y%m%d-%H%M%S')}.json"
    )
    report = {
        "date": datetime.now(timezone.utc).isoformat(),
        "type": "pure_clustering_baseline",
        "no_llm_required": True,
        "n_clusters": len(per_cluster),
        "overall_precision": round(overall_p, 4),
        "overall_recall": round(overall_r, 4),
        "per_cluster": per_cluster,
    }
    with open(out_path, "w") as f:
        json.dump(report, f, ensure_ascii=False, indent=2, default=str)
    print(f"\nReport: {out_path}")


if __name__ == "__main__":
    main()
